version: "3.8"

services:
  nacos1:
    image: nacos/nacos-server:latest
    container_name: nacos1
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=MyNewPassw0rd!
      - MYSQL_SERVICE_DB_NAME=nacos_config
    ports:
      - "8848:8848"
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    restart: on-failure
