version: "2"
services:
  nacos1:
    image: nacos/nacos-server:latest
    network_mode: host
    container_name: nacos1
    environment:
#      - PREFER_HOST_MODE=hostname
      - MODE=standalone  # 单机模式  cluser 是集群模式
#      - NACOS_SERVERS=nacos1:8848,nacos2:8848,nacos3:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.1.100
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=aaaaa888
      - MYSQL_SERVICE_DB_NAME=nacos_config
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    ports:
      - "8848:8848"
    restart: on-failure
