spring:
  application:
    name: demo-app
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR}
        file-extension: yaml
        group: DEFAULT_GROUP
        import-check:
           enabled: false
